[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "NODE_ENV=production node dist/index.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
nodejs_version = "18" 